# This resurces from w3resource

###  NumPy is a Python package providing fast, flexible, and expressive data structures designed to make working with 'relationa' or 'labeled' data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.

## why we are using numpy ruther than list?

provide efficient storage  --> nUmber store in efficient ways

it also provides better ways of handling data for processing  --> 32bit use, 64bit use

it is fast  ---> loop fast process

it is easy to learn --> access easy 

uses relative less memories to store data -->No pointers, occupy required space 


In [8]:
import numpy as np

In [5]:
single=np.array([1,2,3].np.int)

In [6]:
single

array([1, 2, 3])

In [10]:
print(np.__version__)

1.22.3


In [12]:
print(np.show_config())

openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', 

In [13]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [20]:
myarray=np.array([[3,6,4,32],[1,4,5,6]],np.int32)

In [29]:
print(myarray)


print(myarray[0:3,0:2])
print(myarray[0,1])
print(myarray[0][1])

[[ 3  6  4 32]
 [ 1  4  5  6]]
[[3 6]
 [1 4]]
6
6


In [30]:
myarray.shape

(2, 4)

In [31]:
myarray.dtype

dtype('int32')

In [35]:
myarray[0,1]=45
myarray

array([[ 3, 45,  4, 32],
       [ 1,  4,  5,  6]])

## Array creation := 

# conversion from other python structures



In [36]:
list_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
list_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
list_arr.dtype

dtype('int32')

In [39]:
list_arr.shape

(3, 3)

In [40]:
list_arr.size

9

## Intrinsic numpy creation objects

In [43]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
Lspace=np.linspace(1,50,10)  
Lspace


array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [49]:
emp=np.empty((4,5))
emp

array([[1.09363752e-311, 6.22522714e-322, 0.00000000e+000,
        0.00000000e+000, 8.01097888e-307],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 7.06652016e-096],
       [7.06652016e-096, 1.81148490e-152, 9.37041222e-076,
        6.98345624e-077, 6.98345624e-077],
       [1.06239598e-153, 3.98472821e+252, 1.06244660e-153,
        9.78750380e+199, 6.97843734e+252]])

In [51]:
emp_like=np.empty_like(Lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [56]:
ide=np.identity(10)
print(ide)

ide.shape

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


(10, 10)

In [58]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [60]:
arr.ravel()  ## one d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

## Access

In [155]:
# 1D axis -0
# 2D axis- 0, axis-1
# row =axis 0 
# column = axis 1

x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
ar.sum(axis=0)

array([12,  8,  9])

In [77]:
ar.sum(axis=1)

array([ 6, 15,  8])

# Attribute and Methods

visit scipy.org

In [78]:
print(ar)
print(ar.T)  #transpose

[[1 2 3]
 [4 5 6]
 [7 1 0]]
[[1 4 7]
 [2 5 1]
 [3 6 0]]


In [79]:

for item in ar.flat:
    print(item,end=" ")

1 2 3 4 5 6 7 1 0 

In [81]:
ar.ndim

2

In [82]:
ar.size

9

In [83]:
ar.nbytes  ## total bytes consume

36

In [88]:
one=np.array([7,2,4,5,8])

In [89]:
one.argmax() #Return indices of the maximum values along the given axis.

4

In [90]:
one.argmin() #Return indices of the minimum values along the given axis.

1

In [91]:
one.argsort()  #Returns the indices that would sort this array.

array([1, 2, 3, 0, 4], dtype=int64)

In [105]:
print(ar)
for i in ar.flat:
    print(i,end=" ")

[[1 2 3]
 [4 5 6]
 [7 1 0]]
1 2 3 4 5 6 7 1 0 

In [108]:
print("Min Number",ar.min())
print("Min number index ",ar.argmin())
print("Max Number",ar.max())
print("Max Number Index",ar.argmax())



Min Number 0
Min number index  8
Max Number 7
Max Number Index 6
[[0 1 2]
 [0 1 2]
 [2 1 0]]


In [111]:
print(ar.argmax(axis=0)) ### axis=0 ,, 7 num is max , index of 2 ,,5 num max , index-1 ,,, 6 is max index-1
print(ar.argmax(axis=1))

[2 1 1]
[2 2 0]


In [112]:
print(ar.argmin(axis=0))
print(ar.argmin(axis=1))

[0 2 2]
[0 0 2]


In [115]:
print(ar.argsort(axis=0))

print("")

print(ar.argsort(axis=1))

[[0 2 2]
 [1 0 0]
 [2 1 1]]

[[0 1 2]
 [0 1 2]
 [2 1 0]]


In [116]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

## MATHEMATICS 

In [122]:
ar2=np.array([[1,2,2],[4,3,5],[5,7,9]])
print(ar)
print("")
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 1 0]]

[[1 2 2]
 [4 3 5]
 [5 7 9]]


In [121]:
ar+ar2

array([[ 2,  4,  5],
       [ 8,  8, 11],
       [12,  8,  9]])

In [123]:
ar*ar2

array([[ 1,  4,  6],
       [16, 15, 30],
       [35,  7,  0]])

In [132]:
for i in range(len(ar)):
    for j in range(3):
        print(ar[i,j],"+",ar2[i,j] ,"=",ar[i,j]+ar2[i,j])


1 + 1 = 2
2 + 2 = 4
3 + 2 = 5
4 + 4 = 8
5 + 3 = 8
6 + 5 = 11
7 + 5 = 12
1 + 7 = 8
0 + 9 = 9


In [133]:
for i in range(len(ar)):
        print(ar[i],"+",ar2[i] ,"=",ar[i]+ar2[i])

[1 2 3] + [1 2 2] = [2 4 5]
[4 5 6] + [4 3 5] = [ 8  8 11]
[7 1 0] + [5 7 9] = [12  8  9]


In [134]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [136]:
ar.sum()


29

In [146]:
print(np.where(ar>5))
print(type(np.where(ar>5)))

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))
<class 'tuple'>


In [156]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [157]:
np.count_nonzero(ar) # Counts the number of non-zero values in the array ``ar``.

8

In [158]:
np.nonzero(ar)  ## non zero index not show index

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

## Size Difference List and array between

In [159]:
import sys

In [166]:
py_ar=[0,4,55,2] ## regular list

In [167]:
np_ar=np.array(py_ar) ## numpy list

In [168]:
sys.getsizeof(1)*len(py_ar)

112

In [170]:
np_ar.itemsize * np_ar.size

16

## Write a NumPy program to test whether none of the elements of a given array is zero

In [22]:
x=np.array([1,2,3,4])
y=np.array([1,0,3,4])

print(np.any(x)) ## check all elements are non zero --> result is yes
print(np.all(y))

print(np.info(np.all))




True
False
 all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)

Test whether all array elements along a given axis evaluate to True.

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
axis : None or int or tuple of ints, optional
    Axis or axes along which a logical AND reduction is performed.
    The default (``axis=None``) is to perform a logical AND over all
    the dimensions of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a reduction is performed on multiple
    axes, instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternate output array in which to place the result.
    It must have the same shape as the expected output and its
    type is preserved (e.g., if ``dtype(out)`` is float, the result
    will consist of 0.0's and 1.0's). See :ref:`ufuncs-output-type` fo

In [37]:
print(np.all([[True,False],[True,True]]))


print(np.all([[True,False],[True,True]], axis=0))


print(np.all([-1, 0, 5]))


print(np.all([1.0, np.nan]))


print(np.all([[True, True], [False, True]], where=[[True], [False]]))


o=np.array(False)
z=np.all([-1, 4, 5], out=o)
id(z), id(o), z



False
[ True False]
False
True
True


(2271087176528, 2271087176528, array(True))

In [36]:
x1 = np.array([1,0,0,0,0,0])
y1=np.array([0,0,0,0,0,0])
np.any(y1)

## all elements are zer0 than result are False



False

In [38]:
a = np.array([1, 0, np.nan, np.inf])

np.isfinite(a)

array([ True,  True, False, False])

In [39]:
## Write a NumPy program to test element-wise for positive or negative infinity.

np.isinf(a)


array([False, False, False,  True])

In [40]:
### Write a NumPy program to test element-wise for NaN of a given array.

np.isnan(a)

array([False, False,  True, False])

In [42]:
## Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

a=np.array([1+1j,1+0j,4.5,3,2,2j])

print(np.iscomplex(a))
print("Checking for real number:")

print(np.isreal(a))
print("Checking for scalar type:")

print(np.isscalar(3.1))

print(np.isscalar([3.1]))


[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [44]:
### Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.


x = np.array([3, 5])

y = np.array([2, 5])

print("Original numbers:")

print(x)
print(y)

print("Comparison - greater")
print(np.greater(x, y))

print("Comparison - greater_equal")

print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))


Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [51]:
## Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays

x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.1])

print(np.equal(x,y))

print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
False


In [60]:
arr=np.array([1,7,13,105])
print("%d bytes" %(arr.size*arr.itemsize))

16 bytes


In [77]:
## Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
zero=np.zeros(10)
one=np.ones(10)
tens=np.ones(10,dtype='int32')*10
print(tens)
print(one)
print(zero)

[10 10 10 10 10 10 10 10 10 10]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [81]:
rang= np.arange(30,70)
rang

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [82]:
ran= np.arange(30,70,2)
ran

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [85]:
iD= np.identity(3)
iD

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
rand = np.random.normal(0,1,20)

In [91]:
rand

array([ 0.12096419, -0.73317481,  0.29157518, -1.55140732,  0.09967593,
       -1.1983341 ,  0.65282132, -0.77921229, -0.71368624,  0.6577175 ,
       -0.72336665, -1.76642239, -0.18705863, -1.33138678,  0.15432137,
        0.45815395,  1.09491279, -2.22070293, -1.02478004, -0.82630116])

In [96]:
rand = np.random.randn(0,10,2)

In [97]:
rand

array([], shape=(0, 10, 2), dtype=float64)

In [99]:
v = np.arange(15,55)
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [101]:
a = np.arange(10,22).reshape(3,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [103]:
for i in np.nditer(a):
    print(i)

10
11
12
13
14
15
16
17
18
19
20
21


In [110]:
evn = np.linspace(10,49,5)


In [111]:
evn

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

In [123]:
## Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

x= np.arange(21)

x[(x>=9) & (x<=15)] =x[(x>=9) & (x<=15)] *-1
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [127]:
x = np.random.randint(0, 11, 5)

print("Vector of length 5 filled with arbitrary integers from 0 to 10:")

print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[7 0 4 4 2]


In [132]:
a= np.random.randint(1,20,5)
b= np.random.randint(20,30,5)
print(a,b)
a*b

[ 4 17  9 11 12] [24 28 29 22 24]


array([ 96, 476, 261, 242, 288])

In [136]:
b= np.random.randint(10,21,12).reshape(3,4)
b

array([[10, 15, 17, 12],
       [16, 12, 14, 16],
       [19, 20, 15, 10]])

In [137]:
c = np.arange(10,22).reshape(3,4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])